import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Nav from '../src/components/Nav'
import ActorListWrapper from '@/src/components/ActorList'
import ClanList from '@/src/components/ClanList'
import dynamic from 'next/dynamic'

// const LabelPro = dynamic(() => import(('stockbitApp/label')).catch(err => {
//   return <span>Error</span>
// }), { ssr: false });

// const Benefit = dynamic(() => import(('stockbitApp/benefit')).catch(err => {
//   return <span>Error</span>
// }), { ssr: false });

// const Hero = dynamic(() => import(('stockbitApp/hero')).catch(err => {
//   return <span>Error</span>
// }), { ssr: false });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav />
        {/* <Hero /> */}
        {/* <LabelPro /> */}
        <ActorListWrapper />
        {/* <Benefit /> */}
        <ClanList />
      </main>
    </>
  )
}
